Python自定义一个类Student，如下：

```python
class Student():
    ...:     def __init__(self,id,name):
    ...:         self.id = id
    ...:         self.name = name
    ...:     def __repr__(self):
    ...:         return 'id = '+self.id +', name = '+self.name
```

创建实例：xiaoming:

```python
xiaoming = Student('001','xiaoming')
xiaoming() # TypeError: 'Student' object is not callable
```

此时调用实例xiaomng会抛出TypeError实例不能被调用的异常。

重写`__call__` 方法

要想叫xiaoming()调用成功，需要重写__call__方法：

```python
class Student():
    ...:     def __init__(self,id,name):
    ...:         self.id = id
    ...:         self.name = name
    ...:     def __repr__(self):
    ...:         return 'id = '+self.id +', name = '+self.name
    ...:     def __call__(self):
    ...:         print('Now, I can be called')
    ...:         print(f'my name is {self.name}')
```

再次调用xiaoming():

```python
In[1]: xiaoming = Student('001','xiaoming')

In[2]: xiaoming()
OUT[2]: Now, I can be called
my name is xiaoming
```